### PR TITLE
Updating click to use str instead of str (Python 3)

### PR DESCRIPTION
**Pull request by craigmaloney**
Click is receiving the type "unicode" instead of str.

### CODE REVIEW

**Comment by phls** [comment]
Hi, any update?

**Comment by phls** [comment]
ping

**Comment by moggers87** [comment]
Has this been tested in Python 2?

@phls please stop pinging this PR unless you have something useful to add.

**Comment by craigmaloney** [comment]
Honestly I'd given up on this PR. I don't know if it still works as I'm no longer using it.

**Comment by moggers87** [comment]
Good enough for me.

**Comment by craigmaloney** [comment]
Cool. Thanks!

**Pull request merged**
